server:
  port: 9002
  servlet:
    context-path: /api
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
      
spring:
  application:
    name: enquiry
    
  data:
    mongodb:
      database: building
      host: localhost
      username: builder
      password: build
      port: 27017
      authentication-database: building
      
logging:
  level:
    org.springframework.data: info